services:
  # サービス名
  app:
    # コンテナの名前
    container_name: php-apache
    # Dockerfileの場所を指定
    build: ./docker
    # ポート番号
    ports:
      - "8080:80"
    # コンテナとディレクトリを同期
    volumes:
      - ./:/var/www/html/